import Link from 'next/link';
import {readMatchspec} from '../../../lib/contract';
import AssessmentAction from '../../../components/AssessmentAction';
import {displayValue,resultLabel,evidenceLabel,dimensionLabel} from '../../../lib/presentation';
export const dynamic='force-dynamic';
export default async function Pair({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const pairId=Number(id);let pair:any,items:any[]=[],history:any[]=[];
 try{pair=await readMatchspec('get_pair',[pairId]);items=await readMatchspec('get_items',[0,50]) as any[];history=pair.assessment_count?await readMatchspec('get_assessments',[pairId,0,50]) as any[]:[]}catch{return <><div className="eyebrow">MATCHSPEC / CHECK {id}</div><div className="notice" role="alert">We could not load this compatibility check from GenLayer. Try refreshing the page.</div></>}
 const a=items.find(x=>Number(x.id)===Number(pair.item_a)),b=items.find(x=>Number(x.id)===Number(pair.item_b));const verified=history.length>0;const unknown=pair.current_status==='UNKNOWN';
 return <><div className="eyebrow">MATCHSPEC / COMPATIBILITY CHECK {id.padStart(4,'0')}</div><h1 className="title">{a?.manufacturer} {a?.product_name} ↔ {b?.manufacturer} {b?.product_name}</h1><p className="lede">Model {displayValue(a?.model_number)} · Rev {displayValue(a?.revision)} / Model {displayValue(b?.model_number)} · Rev {displayValue(b?.revision)}</p><div className="plate"><div className="eyebrow">{verified?'LATEST VERIFIED RESULT':'CHECK STATUS'}</div><h2>{verified?resultLabel(pair.current_status):'No verified result yet'}</h2>{unknown&&<p>{verified?'The assessment completed successfully, but the configured source did not contain enough information to confirm compatibility for this exact pair.':'No compatibility result has been verified yet. A non-convergent check does not create a result.'}</p>}<dl>{[['Physical fit','current_physical_fit'],['Power','current_power'],['Data','current_data'],['Display','current_display'],['Protocol','current_protocol'],['Adapter requirement','current_adapter_required']].map(([label,key])=><><dt key={label}>{label}</dt><dd>{key==='current_adapter_required'?(pair[key]?'Required':'Not required'):dimensionLabel(String(pair[key]))}</dd></>)}</dl>{verified&&!unknown&&<p>{pair.current_limitation}</p>}</div><p>GenLayer validators will independently read the configured sources and verify the proposed compatibility result. This can take several minutes.</p><AssessmentAction pairId={pairId} initialCount={Number(pair.assessment_count)}/><section className="section"><h2>Evidence used</h2><p>These are the public technical sources GenLayer validators independently read during the assessment.</p>{pair.source_urls.map((u:string)=><p key={u}><a href={u} target="_blank" rel="noreferrer" className="mono">{u}</a></p>)}<p className="mono">Evidence version {pair.source_version}</p></section><section className="section"><h2>Previous checks</h2>{history.length?<table className="table"><thead><tr><th>CHECK #</th><th>RESULT</th><th>EVIDENCE VERSION</th><th>EVIDENCE QUALITY</th></tr></thead><tbody>{history.map((h:any)=><tr key={h.sequence}><td>{h.sequence}</td><td>{resultLabel(h.status)}</td><td>Evidence v{h.source_version}</td><td>{evidenceLabel(h.evidence_state)}</td></tr>)}</tbody></table>:<p>No checks completed yet.</p>}</section><Link href="/pairs">← Back to compatibility</Link></>
}
