'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {MatchspecTransactionError,readMatchspec,writeMatchspec} from '../lib/contract';
import {useWallet,isStudionet} from './WalletProvider';
const explorer=(hash:string)=>`https://explorer-studio.genlayer.com/tx/${hash}`;
export default function AssessmentAction({pairId,initialCount}:{pairId:number;initialCount:number}){
 const {address,chainId,connect}=useWallet();const router=useRouter();const key=`matchspec:assessment:${pairId}`;const [state,setState]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem(key);if(saved){const migrated=saved.replace('Transaction was not accepted.','Consensus did not converge.');localStorage.setItem(key,migrated);queueMicrotask(()=>setState(migrated))}},[key]);
 const persist=(value:string)=>{setState(value);localStorage.setItem(key,value)};
 const run=async()=>{if(!address){await connect();return}if(!isStudionet(chainId)){persist('Switch to Studionet before assessing.');return}setBusy(true);persist('Waiting for wallet approval…');try{persist('Transaction submitted — GenLayer validators are checking the evidence…');const tx=await writeMatchspec(address as `0x${string}`,'assess_compatibility',[pairId]);persist('Finalized — verifying canonical state…');const pair=await readMatchspec('get_pair',[pairId]) as {assessment_count:number};const count=Number(pair.assessment_count);if(count!==initialCount+1)throw new MatchspecTransactionError(`Readback mismatch: expected assessment ${initialCount+1}, observed ${count}.`,tx.hash);const a=await readMatchspec('get_assessment',[pairId,count]) as {pair_id:number;sequence:number};if(Number(a.pair_id)!==pairId||Number(a.sequence)!==count)throw new MatchspecTransactionError('Readback mismatch: assessment identity was not confirmed.',tx.hash);persist(`Check complete — assessment ${count} · ${tx.hash}`);router.refresh()}catch(e){const error=e as Error&{hash?:string};const hash=error.hash;persist(`${error.message||'Assessment failed; canonical state was not changed.'}${hash&&!error.message.includes(hash)?` Transaction: ${hash}`:''}`)}finally{setBusy(false)}};
 const hash=state.match(/0x[a-fA-F0-9]{64}/)?.[0];return <div className="action-row"><button onClick={()=>void run()} disabled={busy}>{busy?'WAITING FOR CONSENSUS…':state?'RUN COMPATIBILITY CHECK AGAIN':'RUN COMPATIBILITY CHECK'}</button>{state&&<p role="status" className="mono">{state}{hash&&<> · <a href={explorer(hash)} target="_blank" rel="noreferrer">VIEW IN EXPLORER</a></>}</p>}</div>;
}
